<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>ShoroCraftLauncher.App</RootNamespace>
    <AssemblyName>ShoroCraftLauncher</AssemblyName>
    <Version>1.5.0</Version>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="8.0.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3967.48" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.11" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ShoroCraftLauncher.Core\ShoroCraftLauncher.Core.csproj" />
    <ProjectReference Include="..\ShoroCraftLauncher.Data\ShoroCraftLauncher.Data.csproj" />
    <ProjectReference Include="..\ShoroCraftLauncher.Infrastructure\ShoroCraftLauncher.Infrastructure.csproj" />
  </ItemGroup>
</Project>
